#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GreatQuotes.Resource", IsApplication=true)]

namespace GreatQuotes
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010003
			public const int Icon = 2130771971;
			
			// aapt resource value: 0x7F010000
			public const int ic_action_discard = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ic_action_edit = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ic_action_new = 2130771970;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int authorText = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int delete_quote = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int edit_quote = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int layout = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int new_quote = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int quoteText = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int saveButton = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int textView2 = 2130837511;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int EditQuote = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int detailOptions = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int mainOptions = 2130968577;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int edit_quote = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
